const mongoose = require('mongoose');

const QuizSchema = new mongoose.Schema({
  lesson: { type: mongoose.Schema.Types.ObjectId, ref: 'Lesson' },
  questions: [{
    type: { type: String, enum: ['mcq', 'truefalse', 'shortanswer'], required: true },
    question: String,
    options: [String],
    answer: mongoose.Schema.Types.Mixed
  }],
  autoGenerated: { type: Boolean, default: false }
});

module.exports = mongoose.model('Quiz', QuizSchema);
